- id: mjml
  name: mjml
  description: Convert MJML email templates to HTML
  entry: mjml_hook
  language: node
  additional_dependencies: [mjml@4.12.0]
  minimum_pre_commit_version: '0'
  files: .*\.mjml
- id: cog
  name: run cog to generate code
  entry: run-cog
  args: [--working-directory-level, '-1']
  language: python
- id: generate-renovate-annotations
  name: generate-renovate-annotations
  description: Generate Renovate tags in environment.yml files
  entry: generate-renovate-annotations
  files: environment[\w-]*\.ya?ml
  args: []
  language: python
